particlesJS("particles-js",{
particles:{
number:{value:90},
color:{value:"#bb00ff"},
shape:{type:"circle"},
opacity:{value:0.6},
size:{value:3},
move:{enable:true,speed:2}
},
interactivity:{
events:{
onhover:{enable:true,mode:"repulse"}
}
}
});
